In [2]:
#ASSIGNMENT 1
population = {
    "shanghai" : "17.8",
    "istanbul" : "13.3 ",
    "karachi" : "13.0",
    "mumbai" : "12.5"
     
}
print(population)

{'shanghai': '17.8', 'istanbul': '13.3 ', 'karachi': '13.0', 'mumbai': '12.5'}


In [4]:
animals = {'dogs':[20,10,15,8,32,15],'cats':[3,4,2,8,2,4],'rabbit':[2,3,3],'fish':[0,3,0,5,0,8,3,1]}
animals['dogs']

[20, 10, 15, 8, 32, 15]

In [5]:
animals['dogs'][3]

8

In [6]:
animals[3]

KeyError: 3

In [8]:
animals['fish']

[0, 3, 0, 5, 0, 8, 3, 1]

In [9]:
a = [1,2,2,3,3,3,4,4,4,4]
b = set(a)
print(len(a)-len(b))

6


In [10]:
tuple_a=3,4
tuple_b=(3,4)
print(tuple_a == tuple_b)
print(tuple_a[1])

True
4


In [11]:
names ={"carrot","albert","ben","donna"}
print("&".join(sorted(names)))

albert&ben&carrot&donna


In [12]:
#Assignment 2
ans = [3,16,33]
guess = [2,15,32]
if guess==ans:
    print("guess is high")
elif guess<ans:
    print("guess is low")
elif guess>ans:
    print("guess is low")

guess is low


In [13]:
for i in range(1,30):
    if(i%5==0):
        print(i)

5
10
15
20
25


In [15]:
#ASSIGNMENT 3
import numpy as np
x=np.array([1,2,3,4])
y=np.array([5.5,6.5,7.5,8.5])
np.add(x,y)

array([ 6.5,  8.5, 10.5, 12.5])

In [16]:
np.subtract(x,y)

array([-4.5, -4.5, -4.5, -4.5])

In [17]:
np.multiply(x,y)

array([ 5.5, 13. , 22.5, 34. ])

In [18]:
np.divide(x,y)

array([0.18181818, 0.30769231, 0.4       , 0.47058824])

In [20]:
import numpy as np
x=np.array([[1,2],[3,4]])
np.sqrt(x)


array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [21]:
np.max(x,axis=0)

array([3, 4])

In [22]:
np.max(x,axis=1)

array([2, 4])

In [23]:
np.median(x,axis=0)

array([2., 3.])

In [24]:
np.median(x,axis=1)

array([1.5, 3.5])

In [25]:
np.std(x,axis=0)

array([1., 1.])

In [26]:
np.std(x,axis=1)

array([0.5, 0.5])

In [27]:
np.mean(x,axis=0)

array([2., 3.])

In [28]:
np.mean(x,axis=1)

array([1.5, 3.5])

In [29]:
np.exp(x)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [30]:
np.power(x,4)

array([[  1,  16],
       [ 81, 256]], dtype=int32)

In [37]:
#ASSIGNEMENT 4
import pandas as pd
data = [{'year':1990,'name':'alice','department':'HR','age':25,'salary':50000},
        {'year':1990,'name':'bob','department':'RD','age':30,'salary':48000},
        {'year':1990,'name':'charlie','department':'admin','age':45,'salary':55000},
        {'year':1991,'name':'alice','department':'HR','age':26,'salary':52000},
        {'year':1991,'name':'bob','department':'RD','age':31,'salary':50000},
        {'year':19991,'name':'charlie','department':'admin','age':46,'salary':60000},
        {'year':1992,'name':'alice','department':'admin','age':27,'salary':60000},
        {'year':1992,'name':'bob','department':'RD','age':32,'salary':520000},
        {'year':1992,'name':'charlie','department':'admin','age':28,'salary':62000}]
data_info=pd.DataFrame(data,index=[0,1,2,3,4,5,6,7,8])
data_info
    

age department     name  salary   year
0   25         HR    alice   50000   1990
1   30         RD      bob   48000   1990
2   45      admin  charlie   55000   1990
3   26         HR    alice   52000   1991
4   31         RD      bob   50000   1991
5   46      admin  charlie   60000  19991
6   27      admin    alice   60000   1992
7   32         RD      bob  520000   1992
8   28      admin  charlie   62000   1992